[external_libraries]
Gio = {min_version = "2.66"}
[options]
girs_directories = ["../gir-files", "../ev-girs"]
library = "PapersShell"
version = "4.0"
min_cfg_version = "4.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true
use_gi_docgen = true
disable_format = false

external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gtk",
   "Pango",
   "PapersDocument",
   "PapersView",
]

generate = [
    "PapersShell.ProgressMessageArea",
    "PapersShell.*",
]

manual = [
    "Adw.Application",
    "Adw.ApplicationWindow",
    "Adw.HeaderBar",
    "Gdk.Display",
    "GdkPixbuf.PixbufFormat",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.Application",
    "Gio.AsyncInitable",
    "Gio.DBusInterface",
    "Gio.DBusInterfaceSkeleton",
    "Gio.DBusObject",
    "Gio.DBusObjectManager",
    "Gio.DBusObjectManagerClient",
    "Gio.DBusObjectProxy",
    "Gio.DBusObjectSkeleton",
    "Gio.DBusProxy",
    "Gio.File",
    "Gio.Initable",
    "Gio.ListModel",
    "Gio.PasswordSave",
    "Gio.Resource",
    "GObject.Object",
    "Gtk.Accessible",
    "Gtk.Align",
    "Gtk.Application",
    "Gtk.ApplicationWindow",
    "Gtk.Buildable",
    "Gtk.ConstraintTarget",
    "Gtk.InfoBar",
    "Gtk.Native",
    "Gtk.PrintOperation",
    "Gtk.Root",
    "Gtk.SearchEntry",
    "Gtk.ShortcutManager",
    "Gtk.Widget",
    "Gtk.Window",
    "PapersDocument.Annotation",
    "PapersDocument.AnnotationType",
    "PapersDocument.Document",
    "PapersDocument.DocumentLicense",
    "PapersDocument.FindOptions",
    "PapersDocument.LinkDest",
    "PapersView.DocumentModel",
    "PapersView.JobFind",
    "PapersView.Metadata",
    "PapersView.SearchContext"
]
